### ISSUE TITLE
Unclear log

### ISSUE THREAD

**Issue by yanivpaz** [advanced-security/spdx-dependency-submission-action#25]
Hi
I am trying to run this action but the log is unclear 
https://github.com/yanivpaz/ghas-bootcamp-javascript/actions/runs/6342063388
 Any idea how to troubleshoot this issue

**Comment by GeekMasher** [comment]
@yanivpaz The logs seem to have been cleaned up, can you replicate this or can I close this?

**Comment by GeekMasher** [comment]
Closing now, please open a new issue if you need more support
