### ISSUE TITLE
Upgrade from Node.js 16 to 20

### ISSUE THREAD

**Issue by parsley72** [advanced-security/spdx-dependency-submission-action#33]
When I run this I get:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: advanced-security/spdx-dependency-submission-action@v0.0.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by GeekMasher** [comment]
@parsley72 This is not fixed with v0.1.0, thanks for raising the issue
